### PR TITLE
feat: added default note on render

### PR DESCRIPTION
**Pull request by AceTheCreator**
This PR also fixed cell id duplication and uncompleted note data when downloaded.

### CODE REVIEW

**Review by steveoni — CHANGES_REQUESTED** [review]
LGTM!

can you fix the file conflict?

**Comment by risenW** [comment]
@AceTheCreator Greate work! One issue though, I pull this branch and tested locally, but when I run start, I get an empty page with no action button:

Screen Shot 2021-05-30 at 4 14 34 PM

**Comment by AceTheCreator** [comment]
@risenW I didn't know what should be in the getting started page, that was why i left it empty.

**Comment by risenW** [comment]
> @risenW I didn't know what should be in the getting started page, that was why i left it empty. 

The first page is to open with a single code cell. So the user can start working from there.

**Comment by AceTheCreator** [comment]
> > @risenW I didn't know what should be in the getting started page, that was why i left it empty.
> 
> The first page is to open with a single code cell. So the user can start working from there.

I'd get that done.

**Pull request closed without merging**
